name: wp_chessboard_interface
description: WhitePawn Chessboard driver interface.
version: 1.0.0
repository: https://github.com/PawnTown/open_chessboard_driver

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  synchronized: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
