import 'package:open_chessboard_driver/open_chessboard_driver.dart';

class Constants {
  static const List<String> squares = [
    'a8',
    'b8',
    'c8',
    'd8',
    'e8',
    'f8',
    'g8',
    'h8',
    'a7',
    'b7',
    'c7',
    'd7',
    'e7',
    'f7',
    'g7',
    'h7',
    'a6',
    'b6',
    'c6',
    'd6',
    'e6',
    'f6',
    'g6',
    'h6',
    'a5',
    'b5',
    'c5',
    'd5',
    'e5',
    'f5',
    'g5',
    'h5',
    'a4',
    'b4',
    'c4',
    'd4',
    'e4',
    'f4',
    'g4',
    'h4',
    'a3',
    'b3',
    'c3',
    'd3',
    'e3',
    'f3',
    'g3',
    'h3',
    'a2',
    'b2',
    'c2',
    'd2',
    'e2',
    'f2',
    'g2',
    'h2',
    'a1',
    'b1',
    'c1',
    'd1',
    'e1',
    'f1',
    'g1',
    'h1'
  ];

  static final Map<String, BoardPiece> defaultPieces = {
    'a1': BoardPiece("R"),
    'b1': BoardPiece("N"),
    'c1': BoardPiece("B"),
    'd1': BoardPiece("Q"),
    'e1': BoardPiece("K"),
    'f1': BoardPiece("B"),
    'g1': BoardPiece("N"),
    'h1': BoardPiece("R"),
    'a2': BoardPiece("P"),
    'b2': BoardPiece("P"),
    'c2': BoardPiece("P"),
    'd2': BoardPiece("P"),
    'e2': BoardPiece("P"),
    'f2': BoardPiece("P"),
    'g2': BoardPiece("P"),
    'h2': BoardPiece("P"),
    'a7': BoardPiece("p"),
    'b7': BoardPiece("p"),
    'c7': BoardPiece("p"),
    'd7': BoardPiece("p"),
    'e7': BoardPiece("p"),
    'f7': BoardPiece("p"),
    'g7': BoardPiece("p"),
    'h7': BoardPiece("p"),
    'a8': BoardPiece("r"),
    'b8': BoardPiece("n"),
    'c8': BoardPiece("b"),
    'd8': BoardPiece("q"),
    'e8': BoardPiece("k"),
    'f8': BoardPiece("b"),
    'g8': BoardPiece("n"),
    'h8': BoardPiece("r"),
  };
}